INSERT INTO EMPLOYEE VALUES('1011','SARTHAK');
INSERT INTO EMPLOYEE VALUES('1012','SARTHAK');
INSERT INTO EMPLOYEE VALUES('1013','MANU');
INSERT INTO EMPLOYEE VALUES('1014','LAMBA');
INSERT INTO EMPLOYEE VALUES('1015','INDER');
INSERT INTO EMPLOYEE VALUES('1016','AKASH');
INSERT INTO EMPLOYEE VALUES('1017','SANYAM');
